// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {astroTokens} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQQOPOOO]OPO'#CeOeOPO'#CfOOOP'#Cg'#CgQTOPOOQTOPOOOOOP,59P,59POmOPO,59POOOP,59Q,59QOrOPO,59QOOOP-E6e-E6eOOOP1G.k1G.kOOOP1G.l1G.l",
  stateData: "w~OPPOSQOVRO~OQVORUO~OTXOUWO~ORZO~OU[O~O",
  goto: "l[PPPPPPPPP]`eRTOVROSTSSOTRYS",
  nodeNames: "⚠ FrontmatterOpen FrontmatterContent FrontmatterClose ExpressionOpen ExpressionContent ExpressionClose HtmlContent Document Frontmatter AstroExpression",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [astroTokens],
  topRules: {"Document":[0,8]},
  tokenPrec: 0
})
